language: en
pipeline: 
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: SklearnIntentClassifier
policies: 
  - name: FormPolicy
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
